export default [{
    "attributes": null,
    "children": [{
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8A21524357831BF101579D4C5DD61552",
                    "pid": "10085",
                    "text": "中赢综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8A21524357831BF101579D4D38C7400F",
                    "pid": "10085",
                    "text": "中赢综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8A2152435AD6A771015ADB34A1003D70",
                    "pid": "10085",
                    "text": "中赢综合三组"
                }],
                "funcdActive": null,
                "id": "10085",
                "pid": "10009",
                "text": "中赢店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "1",
                    "pid": "10086",
                    "text": "西兴综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "100asda",
                    "pid": "10086",
                    "text": "西兴综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "100asda11",
                    "pid": "10086",
                    "text": "西兴综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "100asda1122",
                    "pid": "10086",
                    "text": "西兴综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "100asda112233",
                    "pid": "10086",
                    "text": "西兴综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "100asda11223344",
                    "pid": "10086",
                    "text": "西兴综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "100asda1122334455",
                    "pid": "10086",
                    "text": "西兴综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10147",
                    "pid": "10086",
                    "text": "西兴综合二组"
                }],
                "funcdActive": null,
                "id": "10086",
                "pid": "10009",
                "text": "西兴店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10160",
                    "pid": "10159",
                    "text": "奥体综合组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10161",
                    "pid": "10159",
                    "text": "奥体租赁组（删除）"
                }],
                "funcdActive": null,
                "id": "10159",
                "pid": "10009",
                "text": "奥体店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8A21524357831BF101579D4E19845580",
                    "pid": "8AB398CA5829C3C501583DD7E4B77291",
                    "text": "星耀城租赁组（删除）"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8A21524358BAC7700158C3D5D8AE454B",
                    "pid": "8AB398CA5829C3C501583DD7E4B77291",
                    "text": "星耀城综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8AB398CA57831E2F01579D4BE1B71011",
                    "pid": "8AB398CA5829C3C501583DD7E4B77291",
                    "text": "星耀城综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8AB398CA57831E2F01579D4D90DC154D",
                    "pid": "8AB398CA5829C3C501583DD7E4B77291",
                    "text": "星耀城资管组（删除）"
                }],
                "funcdActive": null,
                "id": "8AB398CA5829C3C501583DD7E4B77291",
                "pid": "10009",
                "text": "星耀城店"
            }],
            "funcdActive": null,
            "id": "10009",
            "pid": "10076",
            "text": "滨江一区（卢莉燕）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10057",
                    "pid": "10089",
                    "text": "潮鸣综合四组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10058",
                    "pid": "10089",
                    "text": "潮鸣综合三组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10153",
                    "pid": "10089",
                    "text": "潮鸣综合五组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "72",
                    "pid": "10089",
                    "text": "潮鸣综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "73",
                    "pid": "10089",
                    "text": "潮鸣综合一组"
                }],
                "funcdActive": null,
                "id": "10089",
                "pid": "10016",
                "text": "潮鸣店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10054",
                    "pid": "10225",
                    "text": "宝善综合四组（删除）"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10177",
                    "pid": "10225",
                    "text": "宝善综合四组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "43",
                    "pid": "10225",
                    "text": "宝善综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "44",
                    "pid": "10225",
                    "text": "宝善综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "60",
                    "pid": "10225",
                    "text": "宝善综合三组"
                }],
                "funcdActive": null,
                "id": "10225",
                "pid": "10016",
                "text": "宝善店"
            }],
            "funcdActive": null,
            "id": "10016",
            "pid": "10076",
            "text": "中一区（杨盛年）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10156",
                    "pid": "10081",
                    "text": "翠苑综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10184",
                    "pid": "10081",
                    "text": "翠苑综合三组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "35",
                    "pid": "10081",
                    "text": "翠苑综合一组"
                }],
                "funcdActive": null,
                "id": "10081",
                "pid": "10018",
                "text": "翠苑店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10138",
                    "pid": "10124",
                    "text": "学军综合一组（撤组）"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8A2152435829883501582D62F2205871",
                    "pid": "10124",
                    "text": "学军综合二组"
                }],
                "funcdActive": null,
                "id": "10124",
                "pid": "10018",
                "text": "学军店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "61",
                    "pid": "10201",
                    "text": "九莲综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "62",
                    "pid": "10201",
                    "text": "九莲综合二组"
                }],
                "funcdActive": null,
                "id": "10201",
                "pid": "10018",
                "text": "九莲店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10139",
                    "pid": "10204",
                    "text": "黄龙综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10222",
                    "pid": "10204",
                    "text": "黄龙综合一组"
                }],
                "funcdActive": null,
                "id": "10204",
                "pid": "10018",
                "text": "黄龙店"
            }],
            "funcdActive": null,
            "id": "10018",
            "pid": "10076",
            "text": "西一区（朱世鹏）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "34",
                    "pid": "10083",
                    "text": "南肖埠综合组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "52",
                    "pid": "10083",
                    "text": "景芳综合一组"
                }],
                "funcdActive": null,
                "id": "10083",
                "pid": "10019",
                "text": "景芳店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10130",
                    "pid": "10084",
                    "text": "采荷综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "53",
                    "pid": "10084",
                    "text": "采荷综合三组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "58",
                    "pid": "10084",
                    "text": "采荷综合一组"
                }],
                "funcdActive": null,
                "id": "10084",
                "pid": "10019",
                "text": "采荷店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10119",
                    "pid": "10109",
                    "text": "近江租赁组(删除)"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "51",
                    "pid": "10109",
                    "text": "近江综合组"
                }],
                "funcdActive": null,
                "id": "10109",
                "pid": "10019",
                "text": "近江店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10179",
                    "pid": "10178",
                    "text": "闸弄口综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10180",
                    "pid": "10178",
                    "text": "闸弄口综合二组"
                }],
                "funcdActive": null,
                "id": "10178",
                "pid": "10019",
                "text": "闸弄口店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10206",
                    "pid": "10199",
                    "text": "钱江新城综合组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10207",
                    "pid": "10199",
                    "text": "钱江新城租赁组（删除）"
                }],
                "funcdActive": null,
                "id": "10199",
                "pid": "10019",
                "text": "钱江新城店"
            }],
            "funcdActive": null,
            "id": "10019",
            "pid": "10076",
            "text": "东区（赵海）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10055",
                    "pid": "10065",
                    "text": "和平综合三组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "41",
                    "pid": "10065",
                    "text": "和平综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "42",
                    "pid": "10065",
                    "text": "和平综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "59",
                    "pid": "10065",
                    "text": "和平综合四组"
                }],
                "funcdActive": null,
                "id": "10065",
                "pid": "10020",
                "text": "和平店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10155",
                    "pid": "10079",
                    "text": "武林综合三组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "65",
                    "pid": "10079",
                    "text": "武林综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "66",
                    "pid": "10079",
                    "text": "武林综合一组"
                }],
                "funcdActive": null,
                "id": "10079",
                "pid": "10020",
                "text": "武林店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10056",
                    "pid": "10080",
                    "text": "朝晖综合四组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10192",
                    "pid": "10080",
                    "text": "朝晖综合五组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "45",
                    "pid": "10080",
                    "text": "朝晖综合三组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "63",
                    "pid": "10080",
                    "text": "朝晖综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "69",
                    "pid": "10080",
                    "text": "朝晖综合一组"
                }],
                "funcdActive": null,
                "id": "10080",
                "pid": "10020",
                "text": "朝晖店"
            }],
            "funcdActive": null,
            "id": "10020",
            "pid": "10076",
            "text": "中二区（周保红）"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10047",
            "pid": "10076",
            "text": "错误/离职帐号222"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10060",
                    "pid": "10102",
                    "text": "滨盛综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10115",
                    "pid": "10102",
                    "text": "滨盛综合一组"
                }],
                "funcdActive": null,
                "id": "10102",
                "pid": "10090",
                "text": "滨盛店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10116",
                    "pid": "10103",
                    "text": "浦沿租赁组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "2",
                    "pid": "10103",
                    "text": "浦沿资管组"
                }],
                "funcdActive": null,
                "id": "10103",
                "pid": "10090",
                "text": "浦沿店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10046",
                    "pid": "10133",
                    "text": "长河资管组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10171",
                    "pid": "10133",
                    "text": "长河租赁组"
                }],
                "funcdActive": null,
                "id": "10133",
                "pid": "10090",
                "text": "长河店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10175",
                    "pid": "10174",
                    "text": "萧山资管组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10176",
                    "pid": "10174",
                    "text": "萧山租赁一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8AB398CA59AF9124015A8787B8BE20FA",
                    "pid": "10174",
                    "text": "萧山租赁二组"
                }],
                "funcdActive": null,
                "id": "10174",
                "pid": "10090",
                "text": "萧山店"
            }],
            "funcdActive": null,
            "id": "10090",
            "pid": "10076",
            "text": "滨江二区（钟亚青）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10157",
                    "pid": "10082",
                    "text": "益乐综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "39",
                    "pid": "10082",
                    "text": "古荡综合一组"
                }],
                "funcdActive": null,
                "id": "10082",
                "pid": "10092",
                "text": "益乐店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10117",
                    "pid": "10104",
                    "text": "文新综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "54",
                    "pid": "10104",
                    "text": "文新综合一组"
                }],
                "funcdActive": null,
                "id": "10104",
                "pid": "10092",
                "text": "文新店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "4",
                    "pid": "10105",
                    "text": "西溪资管组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "6",
                    "pid": "10105",
                    "text": "西溪租赁组"
                }],
                "funcdActive": null,
                "id": "10105",
                "pid": "10092",
                "text": "西溪店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10118",
                    "pid": "10106",
                    "text": "文苑综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "64",
                    "pid": "10106",
                    "text": "文苑综合二组"
                }],
                "funcdActive": null,
                "id": "10106",
                "pid": "10092",
                "text": "文苑店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10194",
                    "pid": "10193",
                    "text": "未来科技城租赁组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10195",
                    "pid": "10193",
                    "text": "未来科技城资管组"
                }],
                "funcdActive": null,
                "id": "10193",
                "pid": "10092",
                "text": "未来科技城店"
            }],
            "funcdActive": null,
            "id": "10092",
            "pid": "10076",
            "text": "西二区（单永淦）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10111",
                    "pid": "10107",
                    "text": "三塘综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "74",
                    "pid": "10107",
                    "text": "三塘综合一组"
                }],
                "funcdActive": null,
                "id": "10107",
                "pid": "10093",
                "text": "三塘店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10114",
                    "pid": "10108",
                    "text": "大关综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "71",
                    "pid": "10108",
                    "text": "大关综合二组"
                }],
                "funcdActive": null,
                "id": "10108",
                "pid": "10093",
                "text": "大关店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10140",
                    "pid": "10121",
                    "text": "米市巷综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "46",
                    "pid": "10121",
                    "text": "米市巷综合一组"
                }],
                "funcdActive": null,
                "id": "10121",
                "pid": "10093",
                "text": "米市巷店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10141",
                    "pid": "10125",
                    "text": "拱宸桥资管组（撤组）"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10142",
                    "pid": "10125",
                    "text": "拱宸桥租赁组（撤组）"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8A21524358686232015870FE91BE0E66",
                    "pid": "10125",
                    "text": "拱宸桥综合组"
                }],
                "funcdActive": null,
                "id": "10125",
                "pid": "10093",
                "text": "拱宸桥店"
            }],
            "funcdActive": null,
            "id": "10093",
            "pid": "10076",
            "text": "北一区（高道华）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "47",
                    "pid": "10087",
                    "text": "浣纱综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "48",
                    "pid": "10087",
                    "text": "清泰综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "49",
                    "pid": "10087",
                    "text": "浣纱综合一组"
                }],
                "funcdActive": null,
                "id": "10087",
                "pid": "10096",
                "text": "浣纱店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10162",
                    "pid": "10088",
                    "text": "庆春三组（取消）"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "67",
                    "pid": "10088",
                    "text": "庆春综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "68",
                    "pid": "10088",
                    "text": "庆春综合一组"
                }],
                "funcdActive": null,
                "id": "10088",
                "pid": "10096",
                "text": "庆春店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10164",
                    "pid": "10110",
                    "text": "复兴综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "50",
                    "pid": "10110",
                    "text": "复兴综合一组"
                }],
                "funcdActive": null,
                "id": "10110",
                "pid": "10096",
                "text": "复兴店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10120",
                    "pid": "10163",
                    "text": "望江综合组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10165",
                    "pid": "10163",
                    "text": "望江租赁组（删除）"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8AB398CA584E8A8201586166B3E35C73",
                    "pid": "10163",
                    "text": "望江综合一组（撤组）"
                }],
                "funcdActive": null,
                "id": "10163",
                "pid": "10096",
                "text": "望江店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8AB398CA5B0B698B015B129C67FE0FA1",
                    "pid": "8A2152435B0B664D015B129C0912007F",
                    "text": "转塘综合一组"
                }],
                "funcdActive": null,
                "id": "8A2152435B0B664D015B129C0912007F",
                "pid": "10096",
                "text": "转塘店"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA58960EE90158A922CF3442B0",
                "pid": "10096",
                "text": "南星桥店（删除）"
            }],
            "funcdActive": null,
            "id": "10096",
            "pid": "10076",
            "text": "南区（吴嘉伟）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10144",
                    "pid": "10127",
                    "text": "申花综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10145",
                    "pid": "10127",
                    "text": "申花综合二组"
                }],
                "funcdActive": null,
                "id": "10127",
                "pid": "10123",
                "text": "申花店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10126",
                    "pid": "10143",
                    "text": "万达综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10148",
                    "pid": "10143",
                    "text": "万达综合二组"
                }],
                "funcdActive": null,
                "id": "10143",
                "pid": "10123",
                "text": "万达店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10211",
                    "pid": "10208",
                    "text": "东三墩综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10212",
                    "pid": "10208",
                    "text": "东三墩租赁组(删除)"
                }],
                "funcdActive": null,
                "id": "10208",
                "pid": "10123",
                "text": "东三墩店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10213",
                    "pid": "10209",
                    "text": "西三墩综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10214",
                    "pid": "10209",
                    "text": "西三墩综合二组"
                }],
                "funcdActive": null,
                "id": "10209",
                "pid": "10123",
                "text": "西三墩店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10215",
                    "pid": "10210",
                    "text": "桥西综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10216",
                    "pid": "10210",
                    "text": "桥西综合一组"
                }],
                "funcdActive": null,
                "id": "10210",
                "pid": "10123",
                "text": "桥西店"
            }],
            "funcdActive": null,
            "id": "10123",
            "pid": "10076",
            "text": "北二区（黄林达）"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10181",
                    "pid": "10173",
                    "text": "沿江综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "5",
                    "pid": "10173",
                    "text": "沿江综合二组"
                }],
                "funcdActive": null,
                "id": "10173",
                "pid": "10172",
                "text": "沿江店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10188",
                    "pid": "10187",
                    "text": "龙湖综合一组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10189",
                    "pid": "10187",
                    "text": "龙湖综合二组"
                }],
                "funcdActive": null,
                "id": "10187",
                "pid": "10172",
                "text": "龙湖店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10217",
                    "pid": "10205",
                    "text": "物美综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "10218",
                    "pid": "10205",
                    "text": "物美综合一组"
                }],
                "funcdActive": null,
                "id": "10205",
                "pid": "10172",
                "text": "物美店"
            }, {
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8AB398CA55D7B1740155E22D12CD1DD8",
                    "pid": "8AB398CA55D7B1740155E22C90E71DD7",
                    "text": "江滨综合二组"
                }, {
                    "attributes": null,
                    "children": null,
                    "funcdActive": null,
                    "id": "8AB398CA55D7B1740155E22DB7461DD9",
                    "pid": "8AB398CA55D7B1740155E22C90E71DD7",
                    "text": "江滨综合一组"
                }],
                "funcdActive": null,
                "id": "8AB398CA55D7B1740155E22C90E71DD7",
                "pid": "10172",
                "text": "江滨店"
            }],
            "funcdActive": null,
            "id": "10172",
            "pid": "10076",
            "text": "下沙区（童丹）"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A2152435AF225DC015AF9134D681FC5",
            "pid": "10076",
            "text": "北三区（梁亚南）"
        }],
        "funcdActive": null,
        "id": "10076",
        "pid": "10198",
        "text": "业务中心"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243591C8CAC01591F7132D11EC2",
                "pid": "10049",
                "text": "服务管家（滨江一区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243591C8CAC01591F73F80C3843",
                "pid": "10049",
                "text": "服务管家（北一区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243591C8CAC01591F74968E5FF8",
                "pid": "10049",
                "text": "服务管家（西一区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243591C8CAC01591F750D1E00D7",
                "pid": "10049",
                "text": "服务管家（西二区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA591C8CDA01591F69D2CB05C9",
                "pid": "10049",
                "text": "服务管家（中一区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA591C8CDA01591F70AF211F36",
                "pid": "10049",
                "text": "服务管家（中二区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA591C8CDA01591F7355C6522D",
                "pid": "10049",
                "text": "服务管家（滨江二区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA591C8CDA01591F7454466BB8",
                "pid": "10049",
                "text": "服务管家（北二区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA591C8CDA01591F755ED77785",
                "pid": "10049",
                "text": "服务管家（东区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA591C8CDA01591F7598E601C6",
                "pid": "10049",
                "text": "服务管家（南区）"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA591C8CDA01591F75D6650C25",
                "pid": "10049",
                "text": "服务管家（下沙区）"
            }],
            "funcdActive": null,
            "id": "10049",
            "pid": "8A215243559D29E501559F0E68AF2904",
            "text": "服务管家组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA559D2ABB01559F293DBC7921",
            "pid": "8A215243559D29E501559F0E68AF2904",
            "text": "服务支持组"
        }],
        "funcdActive": null,
        "id": "8A215243559D29E501559F0E68AF2904",
        "pid": "10198",
        "text": "服务部"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10038",
            "pid": "8A215243559D29E501559F43D61037BB",
            "text": "施工管理组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A215243584E2141015867BA02504DA3",
            "pid": "8A215243559D29E501559F43D61037BB",
            "text": "采购组"
        }],
        "funcdActive": null,
        "id": "8A215243559D29E501559F43D61037BB",
        "pid": "10198",
        "text": "公寓产品部"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10012",
            "pid": "8AB398CA559D2ABB01559F0E2F313CA3",
            "text": "拓盘（CC）部（待删除）"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10052",
            "pid": "8AB398CA559D2ABB01559F0E2F313CA3",
            "text": "客服投诉组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10053",
            "pid": "8AB398CA559D2ABB01559F0E2F313CA3",
            "text": "运营组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10100",
            "pid": "8AB398CA559D2ABB01559F0E2F313CA3",
            "text": "CC组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA584E8A82015867C9AF0B6514",
            "pid": "8AB398CA559D2ABB01559F0E2F313CA3",
            "text": "OBP组"
        }],
        "funcdActive": null,
        "id": "8AB398CA559D2ABB01559F0E2F313CA3",
        "pid": "10198",
        "text": "运营中心"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A215243584E2141015867C2831A644D",
            "pid": "8AB398CA559D2ABB01559F750D3F4EB0",
            "text": "HRBP组"
        }],
        "funcdActive": null,
        "id": "8AB398CA559D2ABB01559F750D3F4EB0",
        "pid": "10198",
        "text": "人事行政部"
    }],
    "funcdActive": null,
    "id": "10198",
    "pid": "00000000000000000000000000000000",
    "text": "杭州城市公司"
}, {
    "attributes": null,
    "children": [{
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A21524358991FC70158A9E9E2E82CF2",
            "pid": "10010",
            "text": "合同审核组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A21524358991FC70158A9EA1E0A38CD",
            "pid": "10010",
            "text": "会计组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A21524358991FC70158A9EA487243C6",
            "pid": "10010",
            "text": "出纳组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA58960EE90158A9EA8EDE2FE0",
            "pid": "10010",
            "text": "核算组"
        }],
        "funcdActive": null,
        "id": "10010",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "财务部"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10014",
            "pid": "10013",
            "text": "官网开发部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10022",
            "pid": "10013",
            "text": "移动开发部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A215243584E2141015867F7119C78BE",
            "pid": "10013",
            "text": "前端部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A215243584E2141015867FAC34B19E9",
            "pid": "10013",
            "text": "UED部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A215243584E2141015867FE98690297",
            "pid": "10013",
            "text": "项目开发部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A215243591C8CAC01593ACB408A72EA",
            "pid": "10013",
            "text": "业务开发一部"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243584E2141015867FD6E1F5E9D",
                "pid": "8A215243591C8CAC01593ACCFC6A4129",
                "text": "后台测试组"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243584E2141015867FDAD205E9E",
                "pid": "8A215243591C8CAC01593ACCFC6A4129",
                "text": "APP测试组"
            }],
            "funcdActive": null,
            "id": "8A215243591C8CAC01593ACCFC6A4129",
            "pid": "10013",
            "text": "测试部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA584E8A82015867F93EB32942",
            "pid": "10013",
            "text": "配置部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA584E8A82015867FCE1E36DA7",
            "pid": "10013",
            "text": "数据开发部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA584E8A82015867FD20D8733A",
            "pid": "10013",
            "text": "架构部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA584E8A82015867FE4B4B1BA5",
            "pid": "10013",
            "text": "运维部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA591C8CDA01593ACBA17A5828",
            "pid": "10013",
            "text": "业务开发二部"
        }],
        "funcdActive": null,
        "id": "10013",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "技术开发中心"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "10024",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "社区产品部"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10029",
            "pid": "10027",
            "text": "招聘部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10030",
            "pid": "10027",
            "text": "HRBP部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A21524356CEEBB80156D11621476F01",
            "pid": "10027",
            "text": "企划部"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A21524358991FC70158AFE7ABBE7426",
                "pid": "8A21524356CEEBB80156D116963404EC",
                "text": "培训组"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA59AF9124015A3FB243E0171C",
                "pid": "8A21524356CEEBB80156D116963404EC",
                "text": "研发组"
            }],
            "funcdActive": null,
            "id": "8A21524356CEEBB80156D116963404EC",
            "pid": "10027",
            "text": "管理学院"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A21524359AF3195015A3FB2858F5B5B",
            "pid": "10027",
            "text": "行政综合部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA56CF28DC0156D1179D5A04AF",
            "pid": "10027",
            "text": "HRCOE部"
        }],
        "funcdActive": null,
        "id": "10027",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "人力资源中心"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "10037",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "采购部"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "10039",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "品牌市场部"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A215243584E21410158680254C4004B",
            "pid": "10149",
            "text": "金融部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA584E8A82015868028B6132C5",
            "pid": "10149",
            "text": "并购部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA584E8A8201586802FB293F4C",
            "pid": "10149",
            "text": "集寓项目部"
        }],
        "funcdActive": null,
        "id": "10149",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "金融并购中心"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A21524358B0189F0158B3543B3F4933",
            "pid": "8A21524357194FA601571C4559F20006",
            "text": "流量运营组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA58B0176B0158B354A4155B97",
            "pid": "8A21524357194FA601571C4559F20006",
            "text": "内部产品运营组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA58B0176B0158B35531577438",
            "pid": "8A21524357194FA601571C4559F20006",
            "text": "外部产品运营组"
        }],
        "funcdActive": null,
        "id": "8A21524357194FA601571C4559F20006",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "线上运营部"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "8A215243584E214101586812E36B1769",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "产品部"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "8A215243598B45AB01598BA86FEA3482",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "产研人事部"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8A21524358B0189F0158B356BA8B61C4",
            "pid": "8AB398CA55BDD5480155BE9EA6C50C72",
            "text": "CC呼叫部"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243598B45AB015991EB30E6559F",
                "pid": "8AB398CA55BDD5480155BE9F5AE20C73",
                "text": "客服对接组"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243598B45AB015991EC02D80A56",
                "pid": "8AB398CA55BDD5480155BE9F5AE20C73",
                "text": "400团队"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA58B0176B0158B476C5AB448A",
                "pid": "8AB398CA55BDD5480155BE9F5AE20C73",
                "text": "管家对接组"
            }],
            "funcdActive": null,
            "id": "8AB398CA55BDD5480155BE9F5AE20C73",
            "pid": "8AB398CA55BDD5480155BE9EA6C50C72",
            "text": "租后服务部"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A21524358B0189F0158B35749236503",
                "pid": "8AB398CA56CF28DC0156D11C331C287A",
                "text": "标准化小组"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A21524358B0189F0158B357FD941788",
                "pid": "8AB398CA56CF28DC0156D11C331C287A",
                "text": "QC组"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA58B0176B0158B35838612B99",
                "pid": "8AB398CA56CF28DC0156D11C331C287A",
                "text": "OBP组"
            }],
            "funcdActive": null,
            "id": "8AB398CA56CF28DC0156D11C331C287A",
            "pid": "8AB398CA55BDD5480155BE9EA6C50C72",
            "text": "业务标准部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA58B0176B0158B35680980B41",
            "pid": "8AB398CA55BDD5480155BE9EA6C50C72",
            "text": "楼盘字典部"
        }, {
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8A215243598B45AB015991E7641406B4",
                "pid": "8AB398CA58B0176B0158B356FEF720D4",
                "text": "业务数据组"
            }, {
                "attributes": null,
                "children": null,
                "funcdActive": null,
                "id": "8AB398CA59889C3B015991E7A80606E9",
                "pid": "8AB398CA58B0176B0158B356FEF720D4",
                "text": "端口数据组"
            }],
            "funcdActive": null,
            "id": "8AB398CA58B0176B0158B356FEF720D4",
            "pid": "8AB398CA55BDD5480155BE9EA6C50C72",
            "text": "数据部"
        }],
        "funcdActive": null,
        "id": "8AB398CA55BDD5480155BE9EA6C50C72",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "线下运营中心"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10035",
            "pid": "8AB398CA56CF28DC0156D13260B95064",
            "text": "设计部"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "8AB398CA58960EE90158A9BEEE581BBD",
            "pid": "8AB398CA56CF28DC0156D13260B95064",
            "text": "督察部"
        }],
        "funcdActive": null,
        "id": "8AB398CA56CF28DC0156D13260B95064",
        "pid": "8A215243559D29E501559F11703D4A81",
        "text": "公寓产品中心"
    }],
    "funcdActive": null,
    "id": "8A215243559D29E501559F11703D4A81",
    "pid": "00000000000000000000000000000000",
    "text": "集团总部"
}, {
    "attributes": null,
    "children": [{
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "10128",
        "pid": "8AB398CA56ABF02A0156B0D639002885",
        "text": "景芳二组（已经撤销）"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "10150",
        "pid": "8AB398CA56ABF02A0156B0D639002885",
        "text": "和平五组（取消）"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "10154",
        "pid": "8AB398CA56ABF02A0156B0D639002885",
        "text": "潮鸣六组（已经撤销）"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10219",
            "pid": "10202",
            "text": "学军2店资管组"
        }, {
            "attributes": null,
            "children": null,
            "funcdActive": null,
            "id": "10220",
            "pid": "10202",
            "text": "学军2店租赁组"
        }],
        "funcdActive": null,
        "id": "10202",
        "pid": "8AB398CA56ABF02A0156B0D639002885",
        "text": "学军2店"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "10221",
        "pid": "8AB398CA56ABF02A0156B0D639002885",
        "text": "黄龙租赁组"
    }, {
        "attributes": null,
        "children": null,
        "funcdActive": null,
        "id": "56",
        "pid": "8AB398CA56ABF02A0156B0D639002885",
        "text": "益乐一组"
    }, {
        "attributes": null,
        "children": [{
            "attributes": null,
            "children": [{
                "attributes": null,
                "children": [{
                    "attributes": null,
                    "children": [{
                        "attributes": null,
                        "children": null,
                        "funcdActive": null,
                        "id": "10129",
                        "pid": "8AB398CA57831E2F0157A3BA53726D41",
                        "text": "清泰二组"
                    }, {
                        "attributes": null,
                        "children": [{
                            "attributes": null,
                            "children": null,
                            "funcdActive": null,
                            "id": "10223",
                            "pid": "10203",
                            "text": "大关2店资管组"
                        }, {
                            "attributes": null,
                            "children": null,
                            "funcdActive": null,
                            "id": "10224",
                            "pid": "10203",
                            "text": "大关2店租赁组"
                        }],
                        "funcdActive": null,
                        "id": "10203",
                        "pid": "8AB398CA57831E2F0157A3BA53726D41",
                        "text": "大关2店"
                    }, {
                        "attributes": null,
                        "children": null,
                        "funcdActive": null,
                        "id": "32",
                        "pid": "8AB398CA57831E2F0157A3BA53726D41",
                        "text": "区政府二组"
                    }, {
                        "attributes": null,
                        "children": null,
                        "funcdActive": null,
                        "id": "33",
                        "pid": "8AB398CA57831E2F0157A3BA53726D41",
                        "text": "区政府一组"
                    }, {
                        "attributes": null,
                        "children": null,
                        "funcdActive": null,
                        "id": "36",
                        "pid": "8AB398CA57831E2F0157A3BA53726D41",
                        "text": "区政府四组"
                    }, {
                        "attributes": null,
                        "children": null,
                        "funcdActive": null,
                        "id": "37",
                        "pid": "8AB398CA57831E2F0157A3BA53726D41",
                        "text": "区政府五组"
                    }, {
                        "attributes": null,
                        "children": null,
                        "funcdActive": null,
                        "id": "38",
                        "pid": "8AB398CA57831E2F0157A3BA53726D41",
                        "text": "区政府三组"
                    }],
                    "funcdActive": null,
                    "id": "8AB398CA57831E2F0157A3BA53726D41",
                    "pid": "8AB398CA57D57C7E0157E6448B5E5A45",
                    "text": "被撤销的组"
                }],
                "funcdActive": null,
                "id": "8AB398CA57D57C7E0157E6448B5E5A45",
                "pid": "8AB398CA57D57C7E0157E64298755A44",
                "text": "被撤销的部门"
            }],
            "funcdActive": null,
            "id": "8AB398CA57D57C7E0157E64298755A44",
            "pid": "8AB398CA57D57C7E0157E6422FCF44B5",
            "text": "被撤销的部门"
        }],
        "funcdActive": null,
        "id": "8AB398CA57D57C7E0157E6422FCF44B5",
        "pid": "8AB398CA56ABF02A0156B0D639002885",
        "text": "被删除被撤销的部门"
    }],
    "funcdActive": null,
    "id": "8AB398CA56ABF02A0156B0D639002885",
    "pid": "00000000000000000000000000000000",
    "text": "测试部门"
}]